# Generated by Django 5.0.4 on 2024-04-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schlname', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='school_regtr',
        ),
    ]
