# Generated by Django 5.0.4 on 2024-04-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appz', '0002_register_delete_school_regtr'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='file',
            field=models.FileField(default=22, upload_to=''),
            preserve_default=False,
        ),
    ]
