# Generated by Django 5.0.4 on 2024-04-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appz', '0003_register_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='formpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('phone_no', models.IntegerField()),
            ],
        ),
    ]
