# Generated by Django 5.0.4 on 2024-04-30 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appz', '0005_form21'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form21',
            old_name='phone',
            new_name='phoneno',
        ),
    ]
