# Generated by Django 5.0.4 on 2024-04-30 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appz', '0006_rename_phone_form21_phoneno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form21',
            old_name='phoneno',
            new_name='phone',
        ),
    ]
