# Generated by Django 5.0.4 on 2024-04-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appz', '0007_rename_phoneno_form21_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='form3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hosp_name', models.CharField(max_length=100)),
                ('hosp_dict', models.CharField(max_length=100)),
                ('hosp_phone', models.IntegerField()),
                ('hosp_address', models.CharField(max_length=100)),
            ],
        ),
    ]
